workers = 1
# bind = '127.0.0.1:8888'
bind = '0.0.0.0:8888'
debug = True
loglevel = 'debug'
errorlog = '/srv/www/menus-prod/logs/g-error.log'
accesslog = '/srv/www/menus-prod/logs/g-access.log'
# django_settings = 'settings.staging'
django_settings = 'settings.prod'
pythonpath = "/srv/www/menus-prod/WeeklyMenus"
